var mongoose = require('mongoose'),
Schema   = mongoose.Schema;

var dictaminacionSchema = new Schema({
  accion_id: { type: String },
  pregunta: [{
    respuesta: { type: Number },
    comentario: { type: String }
  }],
  tecnico:{
    granTotal:{ type: Number },
    totalIII:{ type: Number },
    totalII:{ type: Number },
    totalI:{ type: Number},
    select1:{ type: Number},
    select2:{ type: Number},
    select3:{ type: Number},
    "select3-2":{ type: Number},
    select4:{ type: Number},
    select5:{ type: Number},
    select6:{ type: Number},
    select7:{ type: Number},
    select8:{ type: Number},
    select9:{ type: Number},
    select10:{ type: Number},
    "select10-2":{ type: Number},
    select11:{ type: Number},
    "select11-2":{ type: Number},
    select12:{ type: Number},
    "select12-2":{ type: Number},
    "select12-3":{ type: Number},
    "select12-4":{ type: Number},
    select13:{ type: Number},
    select14:{ type: Number},
    select15:{ type: Number},
    "select15-2":{ type: Number},
    "select15-3":{ type: Number},
    select16:{ type: Number},
    "select16-2":{ type: Number},
    "select16-3":{ type: Number},
    "select16-4":{ type: Number},
    "select16-5":{ type: Number},
    select17:{ type: Number},
    "select17-2":{ type: Number},
    "select17-3":{ type: Number},
    "select17-4":{ type: Number},
    select18:{ type: Number},
    "select18-2":{ type: Number},
    "select18-3":{ type: Number},
    selectA:{ type: Number},
    selectB:{ type: Number},
    "selectB-2":{ type: Number},
    selectC:{ type: Number},
    selectD:{ type: Number},
    "selectD-2":{ type: Number},
    "selectD-3":{ type: Number},
    "selectD-4":{ type: Number},
    "selectD-5":{ type: Number},
    "selectD-6":{ type: Number},
    selectE:{ type: Number},
    "selectE-2":{ type: Number},
    "selectE-3":{ type: Number},
    "selectE-4":{ type: Number},
    selectF:{ type: Number},
    "selectF-2":{ type: Number},
    "selectF-3":{ type: Number},
    selectG:{ type: Number},
    "selectG-2":{ type: Number},
    "selectG-3":{ type: Number},
    selectH:{ type: Number},
    "selectH-2":{ type: Number},
    selectI:{ type: Number},
    selectJ:{ type: Number},
    "txta1": { type: String},
    "txta2":  { type: String},
    "txta3":  { type: String},
    "txta3-2":  { type: String},
    "txta4":  { type: String},
    "txta5":  { type: String},
    "txta6":  { type: String},
    "txta7":  { type: String},
    "txta8":  { type: String},
    "txta9":  { type: String},
    "txta10":  { type: String},
    "txta10-2":  { type: String},
    "txta11":  { type: String},
    "txta11-2":  { type: String},
    "txta12":  { type: String},
    "txta12-2":  { type: String},
    "txta12-3":  { type: String},
    "txta12-4":  { type: String},
    "txta13":  { type: String},
    "txta14":  { type: String},
    "txta15":  { type: String},
    "txta15-2":  { type: String},
    "txta15-3":  { type: String},
    "txta16":  { type: String},
    "txta16-2":  { type: String},
    "txta16-3":  { type: String},
    "txta16-4":  { type: String},
    "txta16-5":  { type: String},
    "txta17":  { type: String},
    "txta17-2":  { type: String},
    "txta17-3":  { type: String},
    "txta17-4":  { type: String},
    "txta18":  { type: String},
    "txta18-2":  { type: String},
    "txta18-3":  { type: String},
    "txtaA":  { type: String},
    "txtaB":  { type: String},
    "txtaB-2":  { type: String},
    "txtaC":  { type: String},
    "txtaD":  { type: String},
    "txtaD-2":  { type: String},
    "txtaD-3":  { type: String},
    "txtaD-4":  { type: String},
    "txtaD-5":  { type: String},
    "txtaD-6":  { type: String},
    "txtaE":  { type: String},
    "txtaE-2":  { type: String},
    "txtaE-3":  { type: String},
    "txtaE-4":  { type: String},
    "txtaF":  { type: String},
    "txtaF-2":  { type: String},
    "txtaF-3":  { type: String},
    "txtaG":  { type: String},
    "txtaG-2":  { type: String},
    "txtaG-3":  { type: String},
    "txtaH":  { type: String},
    "txtaH-2":  { type: String},
    "txtaI":  { type: String},
    "txtaJ":  { type: String},
    dictamen:{ type: String },
    fecha: { type: Date, default: Date.now }
  },
  facilitador:{

    selectfac1:{ type: String },
    txtafac1:{ type: String },    
    selectfac2:{ type: String },
    txtafac2:{ type: String },    
    selectfac3:{ type: String },
    txtafac3:{ type: String },    
    selectfac4:{ type: String },
    txtafac4:{ type: String },
    selectfac5:{ type: String },
    txtafac5:{ type: String },

    dictamen:{ type: String },
    fecha: { type: Date, default: Date.now },
    evaluador:{ type: String }
  },
  puntaje: {type: Number}

},
{
  collection : 'dictaminacion'
}
);

module.exports = mongoose.model('dictaminacion', dictaminacionSchema);